package com.alqaseh.ecommerce.config;

import com.alqaseh.ecommerce.features.auth.dto.response.LoginResponse;
import com.alqaseh.ecommerce.features.order.dto.response.AdminOrderResponse;
import com.alqaseh.ecommerce.features.order.dto.response.CustomerOrderResponse;
import com.alqaseh.ecommerce.features.product.dto.response.AdminProductResponse;
import com.alqaseh.ecommerce.features.product.dto.response.CustomerProductResponse;
import com.alqaseh.ecommerce.shared.response.ApiErrorResponse;
import com.alqaseh.ecommerce.shared.response.ApiResponse;
import com.alqaseh.ecommerce.shared.response.CursorResponse;
import com.alqaseh.ecommerce.shared.response.PageResponse;
import com.fasterxml.jackson.databind.JavaType;
import com.fasterxml.jackson.databind.type.TypeFactory;
import io.swagger.v3.core.converter.AnnotatedType;
import io.swagger.v3.core.converter.ModelConverters;
import io.swagger.v3.core.converter.ResolvedSchema;
import io.swagger.v3.core.util.Json;
import io.swagger.v3.oas.models.Components;
import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.Operation;
import io.swagger.v3.oas.models.examples.Example;
import io.swagger.v3.oas.models.info.Contact;
import io.swagger.v3.oas.models.info.Info;
import io.swagger.v3.oas.models.media.ComposedSchema;
import io.swagger.v3.oas.models.media.Content;
import io.swagger.v3.oas.models.media.MediaType;
import io.swagger.v3.oas.models.media.Schema;
import io.swagger.v3.oas.models.responses.ApiResponses;
import io.swagger.v3.oas.models.security.SecurityScheme;
import org.springdoc.core.customizers.OpenApiCustomizer;
import org.springdoc.core.models.GroupedOpenApi;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.Consumer;

import static com.alqaseh.ecommerce.config.ApiExamples.*;

/**
 * OpenAPI documentation. Paths, parameters, request schemas and security are generated by springdoc from the controllers
 * and DTOs. This class adds what cannot be inferred from a {@code ResponseEntity<?>}: the documented responses of every
 * endpoint (status codes, typed envelope schemas, real examples) and the request examples.
 *
 * <p>The documented cases mirror the real behaviour and nothing else: 401/403 follow from {@code SecurityConfig} and
 * {@code @PreAuthorize}, the 4xx business cases are the {@code ErrorCode}s the services return, the rest comes from
 * {@code GlobalExceptionHandler}. Keep this table in sync when an endpoint changes ({@code OpenApiDocumentationTest} guards it).
 */
@Configuration
public class OpenApiConfig {

    private static final String BEARER = "Bearer Authentication";
    private static final String JSON = "application/json";

    @Bean
    public OpenAPI openAPI() {
        return new OpenAPI()
                .info(new Info()
                        .title("Al Qaseh E-Commerce API")
                        .version("1.0.0")
                        .contact(new Contact().name("Abbas"))
                        .description("""
                                Small e-commerce backend. Pick your role (top-right): **Admin (Dashboard)** or **Customer (App)**. Both include login.

                                - Login with `POST /api/auth/login`, then **Authorize** with the JWT. No/invalid token: `401`; wrong role: `403`.
                                - Success: `{ timestamp, success: true, data }`. Error: `{ timestamp, status, code, message, path, validationErrors? }`; `message` follows `Accept-Language` (`en`, `ar`).
                                - Enums are case-insensitive on input, upper-case on output. Lists: `page` from 0, `size` 1-50 (default 10).
                                """))
                .components(new Components().addSecuritySchemes(BEARER, new SecurityScheme()
                        .type(SecurityScheme.Type.HTTP).scheme("bearer").bearerFormat("JWT")
                        .description("JWT returned by `POST /api/auth/login`")));
    }

    @Bean
    public GroupedOpenApi adminApi() {
        return roleGroup("1-admin", "Admin (Dashboard)", "ADMIN",
                "Endpoints for the **ADMIN** role: manage products, list all orders with cost and profit.");
    }

    @Bean
    public GroupedOpenApi customerApi() {
        return roleGroup("2-customer", "Customer (App)", "CUSTOMER",
                "Endpoints for the **CUSTOMER** role: browse products, place and list own orders.");
    }

    /** Groups the operations whose {@code @PreAuthorize} mentions the role (shared endpoints appear in both groups). */
    private static GroupedOpenApi roleGroup(String group, String displayName, String role, String description) {
        return GroupedOpenApi.builder().group(group).displayName(displayName)
                .pathsToMatch("/api/auth/**", "/api/products/**", "/api/admin/**", "/api/customer/**", "/api/orders/**")
                .addOpenApiMethodFilter(method -> {
                    PreAuthorize rule = method.getAnnotation(PreAuthorize.class);
                    return rule == null /* login: open to both roles */ || rule.value().contains("'" + role + "'");
                })
                .addOpenApiCustomizer(o -> {
                    o.getInfo().description(description);
                    document(o);
                })
                .build();
    }

    @Bean
    public OpenApiCustomizer apiDocumentation() {
        return OpenApiConfig::document;
    }

    /**
     * Documents the shared endpoints: one simple example per response, only the statuses the endpoint can really answer
     * with. Role groups call it themselves: springdoc customizes their paths after the global customizers ran.
     */
    private static void document(OpenAPI openApi) {
        Schema<?> error = register(openApi, ApiErrorResponse.class);
        Schema<?> login = register(openApi, ApiResponse.class, LoginResponse.class);
        Schema<?> productAdmin = register(openApi, ApiResponse.class, AdminProductResponse.class);
        Schema<?> productsAdmin = register(openApi, PageResponse.class, AdminProductResponse.class);
        Schema<?> productsCustomer = register(openApi, CursorResponse.class, CustomerProductResponse.class);
        Schema<?> order = register(openApi, ApiResponse.class, CustomerOrderResponse.class);
        Schema<?> myOrders = register(openApi, PageResponse.class, CustomerOrderResponse.class);
        Schema<?> allOrders = register(openApi, PageResponse.class, AdminOrderResponse.class);

        openApi.getComponents().getSchemas().remove("ApiResponseObject"); // springdoc artefact
        openApi.getComponents().getSchemas().remove("PageResponseObject");
        openApi.getComponents().getSchemas().remove("CursorResponseObject");

        Docs docs = new Docs(openApi, error);

        docs.operation("login", d -> d
                .request(ex("Admin", LOGIN_ADMIN), ex("Customer", LOGIN_CUSTOMER))
                .success(200, "Login successful", login, ex("Logged in", LOGIN_OK))
                .error(400, "Missing fields", ex("VALIDATION_ERROR", VALIDATION_LOGIN))
                .error(401, "Wrong username or password", ex("INVALID_CREDENTIALS", INVALID_CREDENTIALS)));

        docs.operation("createProduct", d -> d
                .request(ex("Product", PRODUCT_REQUEST))
                .success(201, "Product created", productAdmin, ex("Created", PRODUCT_ADMIN))
                .error(400, "Invalid input", ex("VALIDATION_ERROR", VALIDATION_PRODUCT))
                .error(409, "Product name already exists", ex("PRODUCT_NAME_ALREADY_EXISTS", PRODUCT_NAME_EXISTS)));

        docs.operation("updateProduct", d -> d
                .request(ex("Product", PRODUCT_REQUEST))
                .success(200, "Product updated", productAdmin, ex("Updated", PRODUCT_ADMIN))
                .error(400, "Invalid input", ex("VALIDATION_ERROR", VALIDATION_PRODUCT))
                .error(404, "Product not found", ex("PRODUCT_NOT_FOUND", PRODUCT_NOT_FOUND_UPDATE))
                .error(409, "Name already used, or the product was changed at the same time; retry",
                        ex("PRODUCT_NAME_ALREADY_EXISTS", PRODUCT_NAME_EXISTS), ex("CONCURRENT_MODIFICATION", CONCURRENT_MODIFICATION_PRODUCT)));

        docs.operation("listProductsForAdmin", d -> d
                .success(200, "A page of products with cost and exact quantity (page/offset pagination, with totals)", productsAdmin, ex("Products", PRODUCT_PAGE_ADMIN))
                .error(400, "Invalid page, size or category", ex("VALIDATION_ERROR", validationPagination("/api/admin/products"))));

        docs.operation("listProductsForCustomer", d -> d
                .success(200, "A page of products with a stock status (keyset pagination)", productsCustomer, ex("Products", PRODUCT_PAGE_CUSTOMER))
                .error(400, "Invalid limit, cursor or category", ex("VALIDATION_ERROR", validationCursor("/api/customer/products"))));

        docs.operation("createOrder", d -> d
                .request(ex("Credit card with discount code", ORDER_CARD_WITH_DISCOUNT), ex("XYZ wallet", ORDER_WALLET))
                .success(201, "Order placed", order, ex("Created", ORDER_CREATED))
                .error(400, "Invalid input, not enough stock or discount code rejected",
                        ex("VALIDATION_ERROR", VALIDATION_ORDER), ex("INSUFFICIENT_STOCK", INSUFFICIENT_STOCK))
                .error(402, "Payment declined; nothing was changed", ex("PAYMENT_FAILED", PAYMENT_FAILED))
                .error(404, "Product not found", ex("PRODUCT_NOT_FOUND", PRODUCT_NOT_FOUND_ORDER))
                .error(409, "Stock or discount code was taken by another order; retry", ex("CONCURRENT_MODIFICATION", CONCURRENT_MODIFICATION)));

        docs.operation("listMyOrders", d -> d
                .success(200, "Your orders, newest first", myOrders, ex("Orders", MY_ORDERS_PAGE))
                .error(400, "Invalid page or size", ex("VALIDATION_ERROR", validationPagination("/api/orders/my"))));

        docs.operation("listAllOrders", d -> d
                .success(200, "All orders, newest first", allOrders, ex("Orders", ADMIN_ORDERS_PAGE))
                .error(400, "Invalid page, size or filter", ex("VALIDATION_ERROR", validationPagination("/api/orders"))));
    }

    // ------------------------------------------------------------------ helpers

    private record Ex(String name, String json) {
    }

    private static Ex ex(String name, String json) {
        return new Ex(name, json);
    }

    private static JavaType page(Class<?> row) {
        return TypeFactory.defaultInstance().constructParametricType(PageResponse.class, row);
    }

    /** Registers the schema of a (generic) type with its dependencies and returns a reference to it. */
    private static Schema<?> register(OpenAPI openApi, Class<?> raw, Object... typeArguments) {
        TypeFactory types = TypeFactory.defaultInstance();
        JavaType[] args = new JavaType[typeArguments.length];
        for (int i = 0; i < args.length; i++) {
            args[i] = typeArguments[i] instanceof JavaType t ? t : types.constructType((Class<?>) typeArguments[i]);
        }
        JavaType type = args.length == 0 ? types.constructType(raw) : types.constructParametricType(raw, args);
        ResolvedSchema resolved = ModelConverters.getInstance().resolveAsResolvedSchema(new AnnotatedType(type).resolveAsRef(true));
        resolved.referencedSchemas.forEach((name, schema) -> openApi.getComponents().addSchemas(name, schema));
        return resolved.schema;
    }

    private static final class Docs {
        private final OpenAPI openApi;
        private final Schema<?> error;

        Docs(OpenAPI openApi, Schema<?> error) {
            this.openApi = openApi;
            this.error = error;
        }

        void operation(String operationId, Consumer<Doc> declaration) {
            // A role group only contains its own operations; the complete document is checked by OpenApiDocumentationTest.
            Operation operation = openApi.getPaths() == null ? null : openApi.getPaths().values().stream()
                    .flatMap(item -> item.readOperations().stream())
                    .filter(op -> operationId.equals(op.getOperationId()))
                    .findFirst()
                    .orElse(null);
            if (operation == null) {
                return;
            }
            Doc doc = new Doc(operation, error);
            declaration.accept(doc);
            doc.sortResponses();
        }
    }

    private static final class Doc {
        private final Operation operation;
        private final Schema<?> error;
        private final Map<String, io.swagger.v3.oas.models.responses.ApiResponse> responses = new LinkedHashMap<>();

        Doc(Operation operation, Schema<?> error) {
            this.operation = operation;
            this.error = error;
        }

        Doc request(Ex... examples) {
            operation.getRequestBody().getContent().get(JSON).setExamples(examples(examples));
            return this;
        }

        Doc success(int status, String description, Schema<?> schema, Ex... examples) {
            return response(status, description, schema, examples);
        }

        Doc error(int status, String description, Ex... examples) {
            return response(status, description, error, examples);
        }

        private Doc response(int status, String description, Schema<?> schema, Ex... examples) {
            responses.put(String.valueOf(status), new io.swagger.v3.oas.models.responses.ApiResponse()
                    .description(description)
                    .content(new Content().addMediaType(JSON, new MediaType().schema(schema).examples(examples(examples)))));
            return this;
        }

        void sortResponses() {
            ApiResponses sorted = new ApiResponses();
            responses.entrySet().stream().sorted(Map.Entry.comparingByKey())
                    .forEach(e -> sorted.addApiResponse(e.getKey(), e.getValue()));
            operation.setResponses(sorted);
        }

        private static Map<String, Example> examples(Ex... examples) {
            Map<String, Example> map = new LinkedHashMap<>();
            for (Ex e : examples) {
                try {
                    map.put(e.name(), new Example().summary(e.name()).value(Json.mapper().readTree(e.json())));
                } catch (Exception ex) {
                    throw new IllegalStateException("Invalid JSON example: " + e.name(), ex);
                }
            }
            return map;
        }
    }
}
